#!/usr/bin/env bash

# Copyright 2019 Comcast Corporation
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# SPDX-License-Identifier: Apache-2.0

echo "Getting SPDX license data."
[ -d spdx-tools ] && rm -rf spdx-tools
mkdir spdx-tools
cd spdx-tools
git init
git remote add origin https://github.com/spdx/tools.git
git fetch --depth=1 origin master
git config core.sparseCheckout true
mkdir -p .git/info
echo "resources/stdlicenses" >> .git/info/sparse-checkout
git pull origin master
cd ..
[ -d spdx_licenses ] && rm -rf spdx_licenses
mkdir spdx_licenses
for l in $(ls spdx-tools/resources/stdlicenses/*.jsonld); do
	id=$(jq -r .licenseId $l)
	if [ -n $id -a $id != "null" ]; then
		echo "Getting license data for $id."
		txt="$(jq -r .licenseText $l)"
		[ -n "$txt" -a "$txt" != "null" ] && jq -r .licenseText $l > spdx_licenses/$id.txt
		hdr="$(jq -r .standardLicenseHeader $l)"
		[ -n "$hdr" -a "$hdr" != "null" ] && jq -r .standardLicenseHeader $l > spdx_licenses/$id.header.txt
	fi
done

echo "Building dbmaker."
cd dbmaker
go build
cd ..

echo "Compiling licenses into database."
./dbmaker/dbmaker spdx_licenses spdx.db

echo "Embedding database."
cat >licensedb.go <<EOF
// Code generated by make_licenses.sh; DO NOT EDIT

/*
Copyright 2019 Comcast Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package main

var LicenseDBContents []byte = []byte{
EOF


od -A n -t x1 spdx.db | sed 's/^/0x/;s/ //;s/ /,0x/g;s/$/,/' >> licensedb.go

cat >>licensedb.go <<EOF
}
EOF

gofmt -w licensedb.go
